mqtt:
  prefix: 'iotlink/workgroup'
  clientId: 'DESKTOP-PC'
  statsPrefix: 'windows-monitor/stats'
  server: '192.168.1.1'
  port: 1883
  auth:
    user: 'user'
    pass: 'pass'
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: true
    connectMsg: "ON"
    disconnectMsg: "OFF"
control:
  - shutdown
  - restart
  - send-keys
  - notify
  - media
monitoring:
  - cpu
  - memory
  - network_upload
  - network_download
  - media
  - microphone
  - idle
